{
  parserClass="com.github.dgodyna.ijjettemplate.parser.JetParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Jet"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.dgodyna.ijjettemplate.psi"
  psiImplPackage="com.github.dgodyna.ijjettemplate.psi.impl"

  elementTypeHolderClass="com.github.dgodyna.ijjettemplate.psi.JetTypes"
  elementTypeClass="com.github.dgodyna.ijjettemplate.psi.JetElementType"
  tokenTypeClass="com.github.dgodyna.ijjettemplate.psi.JetTokenType"

  tokens = [
   COMMENT              =  ''
   LDOUBLE_BRACE        =  '{{'
   RDOUBLE_BRACE        =  '}}'
   IMPORT               = 'import'
  ]
}


File ::= StatementList

StatementList    ::= ( TEXT+ |ImportStatement )*


ImportStatement  ::= '{{' 'import' StringExpr '}}'
StringExpr     ::= STRING
